name: Run Python Script

on: [push] # This workflow runs on every push to the repository

jobs:
  build:
    runs-on: ubuntu-latest # The type of runner that will run the job

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Action to check out your repository's code

    - name: Set up Python
      uses: actions/setup-python@v5 # Action to set up Python environment
      with:
        python-version: '3.11' # Specify the version of Python you need

    - name: Install dependencies (optional)
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi
    - name: Execute Python script
      env:
        API_KEY: ${{ secrets.penv }}
      run: |
        chmod +x src/main.py
        python src/main.py
    - name: Commit and push changes
      run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add *
          git commit -m "./docs updated" --allow-empty
          git push
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
